language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0
install:
  - dotnet restore prometheus-net.sln
script:
  - dotnet test --configuration Release "prometheus-net.tests/prometheus-net.tests.csproj"