global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 3s

# Local Prometheus collector for testing and dashboard development purposes.

remote_write:
- url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  send_exemplars: true
  basic_auth:
    username: $GRAFANA_USER
    password: $GRAFANA_API_KEY

scrape_configs:
  - job_name: prometheus-net
    scheme: http
    static_configs:
    - targets:
      # Most of the samples use 1234
      - $HOST_IP:1234
      # Sample.Grpc
      - $HOST_IP:5025
      # Sample.Web
      - $HOST_IP:5099
      # Sample.Web.MetricExpiration
      - $HOST_IP:5283
      # Not supported: Sample.Web.NetFramework because IIS Express is localhost-only.